quiz/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .views import QuizListView, CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake, CourseQuizzesProgressDetailView
from .decorators import validate_user_can_access
from .decorators import validate_user_can_access_to_exam

urlpatterns = patterns('',
	url(regex=r'^$', view=login_required(QuizListView.as_view()), name='quiz_index'),
	url(regex=r'^category/$', view=login_required(CategoriesListView.as_view()), name='quiz_category_list_all'),
	url(regex=r'^category/(?P<category_name>[\w.-]+)/$', view=login_required(ViewQuizListByCategory.as_view()), name='quiz_category_list_matching'),
	url(regex=r'^progress/$', view=login_required(QuizUserProgressView.as_view()), name='quiz_progress'),
	url(regex=r'^marking/$', view=login_required(QuizMarkingList.as_view()), name='quiz_marking'),
	url(regex=r'^marking/(?P<pk>[\d.]+)/$', view=login_required(QuizMarkingDetail.as_view()), name='quiz_marking_detail'),
        url(regex=r'^progress/(?P<slug>[\w-]+)/$', view=CourseQuizzesProgressDetailView.as_view(), name='quiz_progress_page'),
 #  passes variable 'quiz_name' to quiz_take view
	url(regex=r'^(?P<slug>[\w-]+)/$', view=validate_user_can_access_to_exam(validate_user_can_access(login_required(QuizDetailView.as_view()))), name='quiz_start_page'),
	url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',view=validate_user_can_access_to_exam(validate_user_can_access(login_required(QuizTake.as_view()))), name='quiz_question'),
)

users/urls.py
from django.conf.urls import patterns, url
from userena.views import signin
from .views import signup
from .decorator_login import signin_decorator

urlpatterns = patterns('',
    url(r'^login/$', signin_decorator(signin), {
        "template_name": "users/login.html", }, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login',
        name="logout"),
    url(r'^signup/$', signup, {"template_name": "users/register.html", },
        name="signup"),
)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from userena.utils import get_profile_model

class UserCreation(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(UserCreation, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({"placeholder": "username"})
        self.fields["email"].widget.attrs.update({"placeholder": "username@hacker.com"})
        self.fields["password1"].widget.attrs.update({"placeholder": "Pon algo que tome siglos romper"})
        self.fields["password2"].widget.attrs.update({"placeholder": "Una vez mas"})

from django import forms
from django.utils.translation import ugettext_lazy as _
from userena import settings as userena_settings
from userena.models import UserenaSignup
from userena.utils import get_user_model


attrs_dict = {'class': 'required'}

USERNAME_RE = r'^[\.\w]+$'

class SignupForm(forms.Form):
    """
    Form for creating a new user account.

    Validates that the requested username and e-mail is not already in use.
    Also requires the password to be entered twice.

    """
    username = forms.RegexField(regex=USERNAME_RE,
                                max_length=30,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Username"),
                                error_messages={'invalid': _('Username must contain only letters, numbers, dots and underscores.')})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("Email"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict,
                                                           render_value=False),
                                label=_("Create password"))
    password2 = forms.CharField(required=False)

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already in use.
        Also validates that the username is not listed in
        ``USERENA_FORBIDDEN_USERNAMES`` list.

        """
        try:
            user = get_user_model().objects.get(username__iexact=self.cleaned_data['username'])
        except get_user_model().DoesNotExist:
            pass
        else:
            if userena_settings.USERENA_ACTIVATION_REQUIRED and UserenaSignup.objects.filter(user__username__iexact=self.cleaned_data['username']).exclude(activation_key=userena_settings.USERENA_ACTIVATED):
                raise forms.ValidationError(_('This username is already taken but not confirmed. Please check your email for verification steps.'))
            raise forms.ValidationError(_('This username is already taken.'))
        if self.cleaned_data['username'].lower() in userena_settings.USERENA_FORBIDDEN_USERNAMES:
            raise forms.ValidationError(_('This username is not allowed.'))
        return self.cleaned_data['username']

    def clean_email(self):
        """ Validate that the e-mail address is unique. """
        if get_user_model().objects.filter(email__iexact=self.cleaned_data['email']):
            if userena_settings.USERENA_ACTIVATION_REQUIRED and UserenaSignup.objects.filter(user__email__iexact=self.cleaned_data['email']).exclude(activation_key=userena_settings.USERENA_ACTIVATED):
                raise forms.ValidationError(_('This email is already in use but not confirmed. Please check your email for verification steps.'))
            raise forms.ValidationError(_('This email is already in use. Please supply a different email.'))
        return self.cleaned_data['email']

    def save(self):
        """ Creates a new user and account. Returns the newly created user. """
        username, email, password = (self.cleaned_data['username'],
                                     self.cleaned_data['email'],
                                     self.cleaned_data['password1'])

        new_user = UserenaSignup.objects.create_user(username,
                                                     email,
                                                     password,
                                                     not userena_settings.USERENA_ACTIVATION_REQUIRED,
                                                     userena_settings.USERENA_ACTIVATION_REQUIRED)
        return new_user


class EditProfileForm(forms.ModelForm):
    """ Base form used for fields that are always required """
    first_name = forms.CharField(label=_(u'First name'),
                                 max_length=30,
                                 required=False)
    last_name = forms.CharField(label=_(u'Last name'),
                                max_length=30,
                                required=False)

    def __init__(self, *args, **kw):
        super(EditProfileForm, self).__init__(*args, **kw)
        # Put the first and last name at the top
        new_order = self.fields.keyOrder[:-2]
        new_order.insert(0, 'first_name')
        new_order.insert(1, 'last_name')
        self.fields.keyOrder = new_order

    class Meta:
        model = get_profile_model()
        exclude = ['user']

    def save(self, force_insert=False, force_update=False, commit=True):
        profile = super(EditProfileForm, self).save(commit=commit)
        # Save first and last name
        user = profile.user
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

        return profile

users/views.py
#-*- coding: UTF-8 -*-
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login, logout
from .forms import UserCreation
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse
from userena.decorators import secure_required
from userena.forms import SignupFormOnlyEmail
from users.forms import EditProfileForm
from .forms import SignupForm
from userena import settings as userena_settings
from emails.utils import SendEmail
from userena.models import UserenaSignup
from userena import signals as userena_signals
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils.translation import ugettext as _
from accounts.models import UserProfile
from functools import wraps
from guardian.shortcuts import assign_perm
from django.conf import settings
mp = settings.MIXPANEL


class UserCreationView(FormView):
    template_name = "users/register.html"
    form_class = UserCreation
    success_url = "/cursos/"

    def get(self, request):
        if request.user.is_authenticated():
            return redirect("/cursos/")
        else:
            form = self.form_class
            return render(request, self.template_name, {"form": form})

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(self.request, user)
        return super(UserCreationView, self).form_valid(form)


def my_decorator(view_func):
    def __decorator(request, *args, **kwargs):
        response = view_func(request, *args, **kwargs)
        if request.method == "POST":
            request.POST["email"]
        return response
    return wraps(view_func)(__decorator)


class ExtraContextTemplateView(TemplateView):
    """ Add extra context to a simple template view """
    extra_context = None

    def get_context_data(self, *args, **kwargs):
        context = super(
            ExtraContextTemplateView, self).get_context_data(*args, **kwargs)
        if self.extra_context:
            context.update(self.extra_context)
        return context

    post = TemplateView.get


@secure_required
def signup(request, signup_form=SignupForm,
           template_name='userena/signup_form.html', success_url=None,
           extra_context=None):
    """
    Signup of an account.

    Signup requiring a username, email and password. After signup a user gets
    an email with an activation link used to activate their account. After
    successful signup redirects to ``success_url``.

    :param signup_form:
        Form that will be used to sign a user. Defaults to userena's
        :class:`SignupForm`.

    :param template_name:
        String containing the template name that will be used to display the
        signup form. Defaults to ``userena/signup_form.html``.

    :param success_url:
        String containing the URI which should be redirected to after a
        successful signup. If not supplied will redirect to
        ``userena_signup_complete`` view.

    :param extra_context:
        Dictionary containing variables which are added to the template
        context. Defaults to a dictionary with a ``form`` key containing the
        ``signup_form``.

    **Context**

    ``form``
        Form supplied by ``signup_form``.

    """
    # If signup is disabled, return 403
    if userena_settings.USERENA_DISABLE_SIGNUP:
        raise PermissionDenied

    # If no usernames are wanted and the default form is used, fallback to the
    # default form that doesn't display to enter the username.
    if userena_settings.USERENA_WITHOUT_USERNAMES and (signup_form == SignupForm):
        signup_form = SignupFormOnlyEmail
    logout(request)
    form = signup_form()
    if request.method == 'POST':
        form = signup_form(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.first_name = request.POST["first_name"]
            user.last_name = request.POST["last_name"]
            user.save()
            userena = UserenaSignup.objects.get(user_id=user)
            to_email, to_name, from_email, from_name, subject, template_name, html_text = (
                request.POST["email"],
                request.POST["first_name"],
                'e@exploiter.co',
                'Cursos de Exploiter.co',
                request.POST["first_name"] + ", Bienvenido a Exploiter.co. Activa tu cuenta",
                '8c18b6f8-f070-4973-acdd-c2b8288b9e9f',
                'http://exploiter.co/accounts/activate/%s/' % userena.activation_key,
                )
            SendEmail(to_email, to_name, from_email, from_name, subject, template_name, html_text)
            l = request.POST["email"]# Send the signup complete signal
            userena_signals.signup_complete.send(sender=None,
                                                 user=user)


            if success_url: redirect_to = success_url
            else: redirect_to = reverse('userena_signup_complete',
                                        kwargs={'username': user.username})

            # A new signed user should logout the old one.
            if request.user.is_authenticated():
                logout(request)

            if (userena_settings.USERENA_SIGNIN_AFTER_SIGNUP and
                not userena_settings.USERENA_ACTIVATION_REQUIRED):
                user = authenticate(identification=user.email, check_password=False)
                login(request, user)

            return redirect(redirect_to)

    if not extra_context: extra_context = dict()
    extra_context['form'] = form
    return ExtraContextTemplateView.as_view(template_name=template_name,
                                            extra_context=extra_context)(request)


@secure_required
def activate(request, activation_key,
             template_name='userena/activate_fail.html',
             retry_template_name='userena/activate_retry.html',
             success_url=None, extra_context=None):
    """
    Activate a user with an activation key.

    The key is a SHA1 string. When the SHA1 is found with an
    :class:`UserenaSignup`, the :class:`User` of that account will be
    activated.  After a successful activation the view will redirect to
    ``success_url``.  If the SHA1 is not found, the user will be shown the
    ``template_name`` template displaying a fail message.
    If the SHA1 is found but expired, ``retry_template_name`` is used instead,
    so the user can proceed to :func:`activate_retry` to get a new actvation key.

    :param activation_key:
        String of a SHA1 string of 40 characters long. A SHA1 is always 160bit
        long, with 4 bits per character this makes it --160/4-- 40 characters
        long.

    :param template_name:
        String containing the template name that is used when the
        ``activation_key`` is invalid and the activation fails. Defaults to
        ``userena/activate_fail.html``.

    :param retry_template_name:
        String containing the template name that is used when the
        ``activation_key`` is expired. Defaults to
        ``userena/activate_retry.html``.

    :param success_url:
        String containing the URL where the user should be redirected to after
        a successful activation. Will replace ``%(username)s`` with string
        formatting if supplied. If ``success_url`` is left empty, will direct
        to ``userena_profile_detail`` view.

    :param extra_context:
        Dictionary containing variables which could be added to the template
        context. Default to an empty dictionary.

    """
    try:
        if (not UserenaSignup.objects.check_expired_activation(activation_key)
            or not userena_settings.USERENA_ACTIVATION_RETRY):
            user = UserenaSignup.objects.activate_user(activation_key)
            if user:
                # Sign the user in.
                auth_user = authenticate(identification=user.email,
                                         check_password=False)
                login(request, auth_user)

                if userena_settings.USERENA_USE_MESSAGES:
                    messages.success(request, _('Your account has been activated and you have been signed in.'),
                                     fail_silently=True)
                try:
                    identify = user.id
                    mp.people_set(identify, {
                        '$first_name'    : user.first_name,
                        '$last_name'     : user.last_name,
                        '$email'         : user.email,
                        'type': 'free'
                    })
                    mp.track(identify, "Account activated")
                except:
                    pass
                if success_url:
                    redirect_to = success_url % {'username': user.username }
                else:
                    redirect_to = reverse('trial_poll')
                return redirect(redirect_to)
            else:
                if not extra_context: extra_context = dict()
                return ExtraContextTemplateView.as_view(template_name=template_name,
                                                        extra_context=extra_context)(
                                        request)
        else:
            if not extra_context: extra_context = dict()
            extra_context['activation_key'] = activation_key
            return ExtraContextTemplateView.as_view(template_name=retry_template_name,
                                                extra_context=extra_context)(request)
    except UserenaSignup.DoesNotExist:
        if not extra_context: extra_context = dict()
        return ExtraContextTemplateView.as_view(template_name=template_name,

templates/users/login.html
{% extends 'base_accounts.html' %}
{% block content %}
<section class="row">
{% if user.is_authenticated %}
    <article style="margin-top: 100px" class="small-12 medium-12 large-6 columns">
    <h4 class="fancy-text-bold">Bienvenido a Exploiter.co</h4>
    <p class="fancy-text">Ya puedes acceder al mejor contenido en español de Hacking. <a href="{% url "courses" %}">Ir a cursos</a></p>
    </article>
{% else %}
<article class="signIn large-5 large-centered columns">
<h2>Iniciar sesión</h2>
    <form method="POST">
        {% csrf_token %}
        {% if form.errors %}
            <center>
                <p>Usuario o contraseña incorrectos</p>
            </center>
        {% endif %}
        <label>
            Email o usuario
            <input type="text" name="identification">
        </label>
        <label>
            Contraseña
            <input type="password" name="password" style="margin-bottom: 0;">
        </label>
        <a class="forgot" href="/accounts/password/reset">Olvidé mi contraseña</a>
        <div class="signInEnter large-6 large-centered columns">
            <input type="submit" class="button expand [tiny small large]" value="ENTRAR">
        </div>

        <div class="or">
            <hr >
            <p>O</p>
        </div>

        <div class="large-10 large-centered columns">
            <div class="content-redes">
                <a class="redes facebook" href='{% url 'social:begin' 'facebook'%}'>Entrar con Facebook</a>
            </div>
        </div>
        <p class="fancy-text">
            ¿Aún no tienes cuenta? ¿Qué esperas? <a href="{% url "signup" %}">¡Regístrate ya!</a>
        </p>
    </form>
    <hr>
</article>
{% endif %}
</section>
{% endblock %}
{% block custom-javascript %}
<script type="text/javascript">
 (function() {
   window._pa = window._pa || {};
   // _pa.orderId = "myOrderId"; // OPTIONAL: attach unique conversion identifier to conversions
   // _pa.revenue = "19.99"; // OPTIONAL: attach dynamic purchase values to conversions
   // _pa.productId = "myProductId"; // OPTIONAL: Include product ID for use with dynamic ads
   var pa = document.createElement('script'); pa.type = 'text/javascript'; pa.async = true;
   pa.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + "//tag.marinsm.com/serve/55e4a3d02ff6c4974600012a.js";
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(pa, s);
 })();
</script>
{% endblock %}

templates/users/register.html
{% extends "base_accounts.html" %}
{% block content %}



<article style="margin-top:20px" class="large-10 large-centered columns">
    <div id="Payment">
        <div class="row purchaseData" style="width: 65%;">
        <form name="user_form" method="POST" data-abide id="user_form" class="form-stacked" accept-charset="UTF-8" action="">{% csrf_token %}
            <h4 style="text-align:left"><span class="formStep">1</span>Tu información básica</h4>
            <div class="large-6 columns">
                <label class="labelPayment" style="font-size: 17px;color: #565656">
                    Nombre
                    <input class="required" id="id_first_name" maxlength="30" name="first_name" type="text" required />
                </label>
                <small class="error">El nombre es obligatorio.</small>
            </div>
            <div class="large-6 columns">
                <label class="labelPayment" style="font-size: 17px;color: #565656">
                    Apellidos
                    <input class="required" id="id_last_name" maxlength="30" name="last_name" type="text" required />
                </label>
                <small class="error">El apellido es obligatorio.</small>
            </div>
            <div class="large-8 columns">
                <label class="labelPayment" style="font-size: 17px;color: #565656">

                    E-mail <small style="font-size:75%;text-transform:lowercase;">(te enviamos un link de activación)</small>
                    <input type="email" id="id_email_paid" maxlength="75" name="email" placeholder="username@exploiter.co" required>
                    <label class="error">
                        {{form.email.errors}}
                    </label>
                </label>
                <p id="id_error_email_paid"></p>
                {% if form_user.email.errors %}
                  <label class="error">
                    {{ form_user.email.errors }}
                  </label>
                {% endif %}
                <small class="error">Se requiere un E-mail.</small>
            </div>
            <hr class="columns">
            <h4  style="text-align:left" class="columns"><span class="formStep">2</span>Tus credenciales de cuenta</h4>
            <div class="large-6 columns">
                <label class="labelPayment" style="font-size: 17px;color: #565656">

                    Usuario
                    <input type="text" id="id_username_paid" name="username" placeholder="usuario" required pattern="[a-zA-Z]+">
                    <label class="error">
                      {{form.username.errors}}
                    </label>
                </label>
                <p id="id_error_username_paid"></p>
                {% if form_user.username.errors %}
                <label class="error">
                  {{ form_user.username.errors }}
                </label>
                {% endif %}
                <small class="error">El nombre de usuario es obligatorio.</small>
            </div>
            <div class="large-6 columns">
                <label class="labelPayment" style="font-size: 17px;color: #565656">

                    Contraseña
                    <input type="password" required id="id_password1_paid" name="password1" placeholder="Pon algo que tome siglos romper">
                    <label class="error">
                      {{form.password1.errors}}
                    </label>
                </label>
                <small class="error">Por favor corrige este campo.</small>
            </div>
            <hr class="columns">
            <div class="large-12 columns" style="text-align:center">
            <input id="signup-button" type="submit" value="Registrarme" class="button [tiny small large]" style="font-size: 16px;">
            </div>
        </form>
      </div>
    <div class="row" style="width: 65%;">
        <div class="or">
            <hr>
            <p>O</p>
        </div>

        <div class="large-10 large-centered columns">
            <div class="content-redes">
                <a class="redes facebook signup" href='{% url 'social:begin' 'facebook'%}'>Registrate con Facebook</a>
            </div>
        </div>
    </div>
</article>


{% endblock %}
{% block custom-javascript %}
<script type="text/javascript">
 (function() {
   window._pa = window._pa || {};
   // _pa.orderId = "myOrderId"; // OPTIONAL: attach unique conversion identifier to conversions
   // _pa.revenue = "19.99"; // OPTIONAL: attach dynamic purchase values to conversions
   // _pa.productId = "myProductId"; // OPTIONAL: Include product ID for use with dynamic ads
   var pa = document.createElement('script'); pa.type = 'text/javascript'; pa.async = true;
   pa.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + "//tag.marinsm.com/serve/55e4a3d02ff6c4974600012a.js";
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(pa, s);
 })();
</script>
{% endblock %}

templates/users/userprofile.html
{% extends 'base.html' %}
{% load user_awards %}
{% load paid_user %}
{% load i18n %}

{% block styles %}
    <meta property="og:title" content="Exploiter.co - mis logros y progreso" />
    <meta property="og:description" content="Mi perfil" />
    <meta property="og:image" content="https://exploiter.co/media/uploads/Anonimato_1.png"/>
{% endblock %}

{% block content %}

{% get_user_award profile.user %}
<h6 class="alert_perfil"><b>¡Importante!</b> sistema de medallas en beta, estamos trabajando para darte la mejor experiencia.</h6>
<section class="bannerUserProfile">

    <div class="large-4 columns">
        <img src="{{ profile.get_mugshot_url }}">
    </div>
    <div class="large-5 columns">
        <p>
          {% if profile.user.get_full_name %}
            {{ profile.user.get_full_name|upper }}
          {% endif %}
        </p>
        <h6>
            <strong>Nickname: </strong>{{ profile.user.username }}
        </h6>
        <h6>
            <strong>Email: </strong>{{ profile.user.email }}
        </h6>
        {% if profile.user.username == user.username %}
        <h6>
            {% get_status_paid profile.user %}
            <strong>Tipo de cuenta: </strong>
            {% if status_paid %}
              {% if end_of_subscription %}
                Profesional, vence el {{ end_of_subscription }}
              {% else %}
                Tú suscripción se venció
              {% endif%}
            {% else %}
               <a class="free" href="{% url 'pricing' %}">Gratis</a>
            {% endif %}
        </h6>
        <a class="custom-button" href="edit">Editar</a>
        {% else %}
            <!-- <a class="custom-button" href="edit">Añadir a mi grupo</a> -->
        {% endif %}
    </div>
    <div class="large-3 columns">
        <div class="points">
            <p>
            {{ points}} <br>Puntos
            </p>
        </div>
    </div>
</section>

<!-- Medallas especiales -->
{% get_award_special_of_user profile.user %}
{% if awards_specials_of_user %}
  <section class="bannerClass bannerBadgeCourse arrow_box">
      <div class="containerClass">
          <div class="caja2 badgeCourse">
              <!-- imagen de medalla especial -->
              <img src="/static/img/ruta_de_imagen">
          </div>
          <div class="caja1">
              <h4 class="fancy-text-bold">Medallas Especiales</h4>
              <div class="showBadges">
                  <a id="medallas-especiales">Ver medallas</a>
              </div>
          </div>
      </div>
  </section>

  <section data-course='medallas-especiales' class="bannerBadges bubble row">
    {% for award in awards_specials_of_user %}
      <div class='contentBadge'>
        <img class='badge {% if not award.date %}gray{% endif %}' src='{{ MEDIA_URL }}{{ award.award.image }}'>
        <h6>{{ award.award.name_show }}</h6>
        {% if award.date %}
          <p>{{ award.date }}</p>
        {% endif %}
      </div>
    {% endfor %}
  </section>
{% endif %}
<!-- Fin Medallas especiales-->

{% for course in courses %}
<section class="bannerClass bannerBadgeCourse arrow_box">
    <div class="containerClass">
        <div class="caja2 badgeCourse">
            <img src="{{ MEDIA_URL }}{{ course.image}}">
        </div>
        <div class="caja1">
            <h4 class="fancy-text-bold">{{ course.name|escape }}</h4>
            <div class="showBadges">
                <a id="{{ course.name|escape }}">Ver medallas</a>
            </div>
        </div>
    </div>
</section>

<section data-course='{{ course.name|escape }}' class="bannerBadges bubble row {% if forloop.counter0 == 0 %}active{% endif%}">
        {% for class in course.courseclass_set.all|dictsort:"id" %}
          {% get_award_of_user class %}
            {% if award_name %}
            <div class="contentBadge">
              <img class="badge {% if not award_date %}gray{% endif %}" src="{{ MEDIA_URL }}{{ award_image }}">
              <h6>{{ award_name }}</h6>
              {% if award_date %}
                <p>{{ award_date }}</p>
              {% endif %}
            </div>
            {% endif %}
        {% endfor %}
</section>

{% endfor %}
{% endblock %}